// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egtsyrpgtxjomnsqpqpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVndHN5cnBndHhqb21uc3FwcXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjE1NjYsImV4cCI6MjA2NjkzNzU2Nn0.P4PEkbt0sZNXqq-6AVYU6otmBSaOq1aVRyLE-rMU71o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});